#!/bin/sh
# zig as host C compiler; tools built as extensionless names also get a .exe twin
Z=/c/Users/andre/.local/zig-x86_64-windows-0.16.0/zig.exe
out=""; prev=""
for a in "$@"; do [ "$prev" = "-o" ] && out="$a"; prev="$a"; done
"$Z" ${ZIGMODE:-cc} -target x86_64-windows-gnu -Wno-date-time -Wno-error=date-time "$@" || exit $?
case "$out" in *.*|"") ;; *) [ -f "$out" ] && cp -f "$out" "$out.exe";; esac
